name: Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2025, macos-15-intel, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Prepare Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt --component clippy
      - name: Check Rust formatting
        run: cargo +stable fmt --check
      - name: Test Rust
        run: cargo +stable test --locked
      - name: Check Rust diagnostics
        run: cargo +stable clippy --locked --all-targets -- -D warnings

  docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Build Docker image
        run: docker build -t sdu-infohelper:ci .
      - name: Smoke test container
        run: docker run --rm sdu-infohelper:ci --version
