name: Check

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  CARGO_HOME: ${{ github.workspace }}/.cache/cargo
  CARGO_TARGET_DIR: ${{ github.workspace }}/target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Prepare Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt --component clippy
      - name: Check Rust formatting
        run: cargo +stable fmt --check
      - name: Test Rust
        run: cargo +stable test --locked
      - name: Check Rust diagnostics
        run: cargo +stable clippy --locked --all-targets -- -D warnings
